# Generated by Django 4.0.5 on 2022-06-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_wiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_answer_text', models.CharField(max_length=10000)),
            ],
        ),
    ]
