# Generated by Django 4.0.5 on 2022-06-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_wiz', '0002_translation_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation_answer',
            name='translation_question_text',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='string_wiz.translation_question'),
        ),
    ]
